### PR TITLE
Feature/SER-151 GET thread/:originalMessageId endpoint

### PR DESCRIPTION
**Pull request by sirctseb**
#### What's this PR do?
Add a `GET /thread/:originalMessageId` to retrieve all of a user's messages sharing that `originalMessageId`

#### Related JIRA tickets:
[SER-151](https://jira.amida-tech.com/browse/SER-151)

#### How should this be manually tested?
1. Populate a thread by sending a message and replying to that message
1. Call `GET /thread/:originalMessageId` and check that all the messages owned by the caller with that originalMessageId are returned.

#### Screenshots (if appropriate):

### CODE REVIEW

**Review by jsachs — CHANGES_REQUESTED** [review]
LGTM, one other test case/behavior definition I would like to see--what happens if you request an original message you are not allowed to see?

**Comment by sirctseb** [comment]
@jsachs 404 I think when the Message scope filters everything out and the findAll comes back with an empty list. Does that behavior sound right, or would a 401 be better? Either way I'll add a test case

**Comment by sirctseb** [comment]
I think 404 is correct. A thread at `/:originalMessageId` is not forbidden to the caller if they don't own any messages that match, there just aren't any messages in that thread for the user. A thread could, in fact, be returned from that exact url if someone else replies to that thread and includes the user. Theoretically HTTP 204 might also be appropriate for these cases

**Review by jsachs — APPROVED** [review]
Behavior sounds good to me.

**Review by ElijahGeorge — APPROVED** [review]
LGTM. Thanks for this @sirctseb

**Pull request merged**
