### PR TITLE
DEVOPS-270 / Environmental renaming.

### PR DESCRIPTION
**Pull request by jmfadeley**
This PR is part of a series to streamline certain environmental variables. 

Please pull, run all tests, verify no interruption to your current services. Run tests, ensure that not of the config files are broken. 

**Note that due to a recent update, you may have to remove the "prepublish" command from `package.json` to run this until this is fixed: https://jira.amida-tech.com/browse/DEVOPS-275**

### CODE REVIEW

**Comment by jmfadeley** [comment]
Closing. Will reopen following testing with universal .env file.

**Comment by mountHouli** [comment]
Typo in `README.md`:

"`MESSAGING_SERVICE_PG_CERT_CA` If ssl is enabled with `MESSAGING_SERVICE_PG_SSL` this can be set to a certificate to override the CAs trusted while initiating"

"trusted" what? Certificate?

**Comment by orndorffgrant** [comment]
@mountHouli I think that was me: is "...override the CAs *that are* trusted..." better?

**Comment by jmfadeley** [comment]
**This PR was closed and a new one was created by accident. Please use https://github.com/amida-tech/amida-messaging-microservice/pull/57 instead for testing this.**

**Comment by mountHouli** [comment]
@jmfadeley this PR is #57 . Did you mean to say "Please use SOME_OTHER_NUMBER instead for testing this." ?

**Comment by mountHouli** [comment]
@orndorffgrant Ahh, yes.

**Comment by jmfadeley** [comment]
**Sorry, I meant https://github.com/amida-tech/amida-messaging-microservice/pull/58.**

**Pull request closed without merging**
